### ISSUE TITLE
Problem with 6.0+ version

### ISSUE THREAD

**Issue by emancypage** [druteika/oxid_modules_config#2]
there is a problem with model/oxpsmodulesconfigstorage.php. 
Here is deprecated method $oDb->getArray...
I suggest change that to $oDb->getAll...

**Comment by druteika** [comment]
@emancypage , this is a valid issue indeed - my old version of Modules Config is not working on v6.
Please try new official fork https://github.com/OXIDprojects/oxid_modules_config, which is actual current version and it includes v6 support, as well as lots of features, such as console based commands and yaml format!

**Comment by emancypage** [comment]
Thank you for this link... 👍 I didn't know that the official site support this solution :) 
Have a nice day!
